title: "Deep Reinforcement Learning for Competitive Agents in MicroRTS: Architecture, Training, and Tournament Evaluation"
description: "Supplementary Materials for Work-In-Progress Paper"
author: "Mathis Delsart"
theme: jekyll-theme-cayman
